### ISSUE TITLE
Force overwrite option

### ISSUE THREAD

**Issue by freshp** [tommy-muehle/tooly-composer-script#3]
I use tooly to load phpunit as phar. Some of my requirements also load phpunit, but via composer. Tooly runs as post command and composer has already created the phpunit file in my bin directory. The the post command  asks, if I want to overwrite phpunit. How can I force this use case for a continuous integration server for example?

**Comment by tommy-muehle** [comment]
Thanks @freshp for the feedback. I have an idea with the "prefer-source" option.
I will publish a new version separately as a new branch soon, so you can test this enhancement.

**Comment by tommy-muehle** [comment]
@freshp 
I create a new branch release/1.1.0 and pushed some changes. Can you please test this version? 

Perhaps with "tm/gpg-verifier": "8a23888d17e945ffc40d9d808d0b4db2c4fec148" as requirement.

**Comment by tommy-muehle** [comment]
I added an new option "force-replace" for this requirement.

**Comment by freshp** [comment]
thx. works very well
