### ISSUE TITLE
Handle unreachable download URLs with timeout and hint

### ISSUE THREAD

**Issue by hollodotme** [tommy-muehle/tooly-composer-script#6]
I shortly had the case, that the URL to the codecept.phar was offline for a while. Tooly's reaction after some seconds of trial is:

```
Script Tooly\ScriptHandler::installPharTools handling the post-update-cmd event terminated with an exception


  [ErrorException]
  sha1_file(http://codeception.com/codecept.phar): failed to open stream: HTTP request failed!
```

Unfortunately codecept was the first tool in my list, so all the following tools were not processed.

IMO this should be handled with an appropriate timeout / error handling for the HTTP operation and a hint like:

`INFO: http://codeception.com/codecept.phar seems down at the moment - skipping.`

Would also be nice for offline work. When travelling with 🇩🇪 🚆 , you know. 😄 

And it may be useful to optionally let one overwrite the default timeout (I guess 5 seconds is an appropriate value) for each tool in composer.json's extra section, like this:

``` json
"tools": {
    "codecept": {
        "url": "http://codeception.com/codecept.phar",
        "only-dev": true,
        "timeout": 10
    }
}
```

**Comment by tommy-muehle** [comment]
I could solve this problem with 3 additional lines. So i remove the current milestone and will release it today in version "1.2.3". 

In case a timeout returns you get the already existing notice "At least one given URL are not accessible!" because it can be the file- or signature-url for this tool.
